[WIP] - Added the possibility to output report in cli
AlexanderMoskovkin/qunit-harness pull request #42
Opened 2017-06-21 13:48 UTC by kirovboris

2017-06-22 06:46 UTC, kirovboris commented
/cc @AlexanderMoskovkin

2017-06-22 09:08 UTC, AlexanderMoskovkin requested changes
Please add some minimal info about new api in README before merge or when it's merged

2017-06-22 09:08 UTC, AlexanderMoskovkin commented on Gulpfile.js
> +            { browserInfo: browsers['ie'], browserName: 'ie' },
let's don't rely on installed browsers. Usually Chrome exists on all almost machines, so let's test it in two Chrome instances

2017-06-22 09:08 UTC, AlexanderMoskovkin commented on src/cli/job.js
> +        this.id = browser.browserName;
regarding my previous comment maybe it's better to add some counter to the `id` since it can be run in several browsers with the same name (like `chrome`)?

2017-06-22 09:08 UTC, AlexanderMoskovkin commented on Gulpfile.js
> +gulp.task('cli', ['lint', 'build'], function (done) {
let's run this task on Travis too

2017-06-29 10:18 UTC, kirovboris commented on Gulpfile.js
> +gulp.task('cli', ['lint', 'build'], function (done) {
How do we run this task on Travis if it requires local installed browsers :open_mouth:?

2017-06-29 10:30 UTC, kirovboris commented on src/cli/job.js
> +        this.id = browser.browserName;
How are you going to find out an error correspond to browser instance. In other word you will have one-to-many relationship.  Besides, you can use now:
```js
{ ..., browserName: 'chrome_56.234234' },
{ ..., browserName: 'chrome_57.223423 }'
```
Or am I missing something?

2017-06-29 11:03 UTC, AlexanderMoskovkin commented on Gulpfile.js
> +gulp.task('cli', ['lint', 'build'], function (done) {
https://devexpress.github.io/testcafe/documentation/recipes/running-tests-in-firefox-and-chrome-using-travis-ci.html

2017-06-29 11:05 UTC, kirovboris commented on Gulpfile.js
> +gulp.task('cli', ['lint', 'build'], function (done) {
got it

2017-06-29 11:30 UTC, AlexanderMoskovkin approved these changes

2017-12-28 14:18 UTC, AlexanderMoskovkin approved these changes

2017-12-28 14:18 UTC, merged