update: replaced request and wd
AlexanderMoskovkin/qunit-harness pull request #63
Opened 2024-01-29 13:48 UTC by Bayheck

2024-02-13 13:57 UTC, Aleksey28 requested changes

2024-02-13 13:57 UTC, Aleksey28 commented on src/saucelabs/job.js
> +
remove this row

2024-02-13 13:57 UTC, Aleksey28 commented on src/saucelabs/job.js
> +                hostname:               'ondemand.saucelabs.com',
Create a constant variable SAUCE_API_HOST for saucelabs.com and replace all appearance with it

2024-02-13 13:57 UTC, Aleksey28 commented on src/saucelabs/job.js
> +                port:                   80,
Create a constant variable SAUCE_API_PORT for port

2024-02-14 13:48 UTC, Aleksey28 approved these changes

2024-02-15 08:04 UTC, kirovboris approved these changes

2024-02-15 08:04 UTC, merged